---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  # --- DEBIAN 12 (Bookworm) ---
  - name: docker-debian12
    image: debian:12
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/lib/systemd/systemd"

  # --- DEBIAN 13 (Trixie) ---
  - name: docker-debian13
    image: debian:13
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/lib/systemd/systemd"

  # --- UBUNTU 22.04 (Jammy) ---
  - name: docker-ubuntu2204
    image: ubuntu:22.04
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/lib/systemd/systemd"

  # --- UBUNTU 24.04 (Noble) ---
  - name: docker-ubuntu2404
    image: ubuntu:24.04
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/lib/systemd/systemd"

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  config_options:
    defaults:
      interpreter_python: auto_silent

verifier:
  name: ansible
